version: "3.8"
services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wg-easy
    volumes:
      - ./wg-/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    environment:
      - WG_HOST=193.42.112.83
      - PASSWORD_HASH=$$2y$$05$$zvpxL0aPd8wwi6l5kM9rQuof9aH8yrutA40glpGjyVnNnt8h7mlL2
      - WG_DEFAULT_DNS=1.1.1.1
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
